### ISSUE TITLE
데이터베이스 활용 아이디어

### ISSUE THREAD

**Issue by Hyunjae-r** [iot-nextop/A-#4]
제가 생각한 데이터베이스 활용방안: 마지막으로 물을 준 날짜를 저장해둠으로써 물을 준지 얼마나 지났는지 확인이 가능하도록 하는 것입니다.
이외에 데이터베이스 활용을 위한 아이디어가 있으시면 댓글을 남겨주세요.

**Comment by KimMyoungSeop** [comment]
시간별 온습도 저장, 공기순환 팬 속도 측정해서 팬이 계속 돌아가는지 확인 또는 속도조절을 통한 온도조절
